name: sakhi_sahayak
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  flutter_sound: ^9.2.13
  permission_handler: ^11.0.1
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  flutter_secure_storage: ^9.0.0
  dio: ^5.4.0
  provider: ^6.1.1
  flutter_svg: ^2.0.9
  record: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/icons/

